// Set to false once Firebase is configured and you have real data
export const USE_MOCK_DATA = true;

const ts = (hoursAgo) => ({
  toDate: () => new Date(Date.now() - hoursAgo * 60 * 60 * 1000),
});

// ─── Users ────────────────────────────────────────────────────────────────────

export const MOCK_USERS = {
  guest:       { uid: 'guest',       displayName: 'Demo User', photoURL: 'https://i.pravatar.cc/150?img=12' },
  mock_eva:    { uid: 'mock_eva',    displayName: 'Eva W.',    photoURL: 'https://i.pravatar.cc/150?img=47' },
  mock_yujen:  { uid: 'mock_yujen', displayName: 'Yujen L.',  photoURL: 'https://i.pravatar.cc/150?img=33' },
  mock_alex:   { uid: 'mock_alex',   displayName: 'Alex C.',   photoURL: 'https://i.pravatar.cc/150?img=15' },
  mock_priya:  { uid: 'mock_priya',  displayName: 'Priya S.',  photoURL: 'https://i.pravatar.cc/150?img=5'  },
  mock_jordan: { uid: 'mock_jordan', displayName: 'Jordan K.', photoURL: 'https://i.pravatar.cc/150?img=64' },
  mock_maya:   { uid: 'mock_maya',   displayName: 'Maya R.',   photoURL: 'https://i.pravatar.cc/150?img=41' },
};

// Derived lookup maps — import these in FeedView, PinDetail, PostComments
export const SAVER_PHOTOS = Object.fromEntries(
  Object.entries(MOCK_USERS).map(([uid, u]) => [uid, u.photoURL])
);
export const SAVER_NAMES = Object.fromEntries(
  Object.entries(MOCK_USERS).map(([uid, u]) => [uid, u.displayName.split(' ')[0]])
);

// ─── Pins ─────────────────────────────────────────────────────────────────────

export const MOCK_PINS = [
  // ── Stanford: Coffee ────────────────────────────────────────────────────────
  {
    id: 'mock1',
    title: 'Coupa Café',
    note: 'Get the cortado — ask for oat milk. Best spot to work before 11am, it gets packed after that.',
    category: 'coffee',
    photoURL: 'https://picsum.photos/seed/coupa_gsb/600/400',
    lat: 37.4281, lng: -122.1651,
    locationName: 'School of Business, Stanford',
    authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL,
    createdAt: ts(2),
    saveCount: 14,
    savedBy: ['mock_yujen', 'mock_alex', 'guest', 'mock_priya'],
  },
  {
    id: 'mock8',
    title: 'Philz Coffee',
    note: 'Iced Silken Splendor, no sugar. The patio in the back is underrated — sunny until about 2pm.',
    category: 'coffee',
    photoURL: 'https://picsum.photos/seed/philz_patio/600/400',
    lat: 37.4421, lng: -122.1601,
    locationName: '855 El Camino Real, Palo Alto',
    authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL,
    createdAt: ts(100),
    saveCount: 9,
    savedBy: ['guest', 'mock_priya'],
  },
  {
    id: 'mock14',
    title: 'CoHo Late Night',
    note: 'Open until midnight most nights. After 9pm it gets weirdly cozy — grad students, people who forgot to eat, good energy. The grilled cheese is worth it.',
    category: 'coffee',
    photoURL: 'https://picsum.photos/seed/coho_midnight/600/400',
    lat: 37.4245, lng: -122.1692,
    locationName: 'Coffee House, Tresidder Union, Stanford',
    authorId: 'mock_jordan', authorName: 'Jordan K.', authorPhoto: MOCK_USERS.mock_jordan.photoURL,
    createdAt: ts(16),
    saveCount: 17,
    savedBy: ['mock_eva', 'mock_yujen', 'mock_alex', 'guest', 'mock_maya'],
  },
  {
    id: 'mock16',
    title: 'Sightglass Coffee',
    note: 'Best light in SF. Two-story with huge industrial windows, quiet on weekday mornings. Worth the BART ride.',
    category: 'coffee',
    photoURL: 'https://picsum.photos/seed/sightglass_soma/600/400',
    lat: 37.7804, lng: -122.4063,
    locationName: '270 7th St, SoMa, San Francisco',
    authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL,
    createdAt: ts(54),
    saveCount: 13,
    savedBy: ['mock_priya', 'mock_jordan', 'mock_yujen'],
  },
  {
    id: 'mock27',
    title: 'CoHo Morning Counter',
    note: 'The one row of stools facing outside by the pastry case. Get there before 9am. Latte is surprisingly good, and the muffins are fresh.',
    category: 'coffee',
    photoURL: null,
    lat: 37.4244, lng: -122.1690,
    locationName: 'Coffee House, Stanford',
    authorId: 'mock_maya', authorName: 'Maya R.', authorPhoto: MOCK_USERS.mock_maya.photoURL,
    createdAt: ts(230),
    saveCount: 5,
    savedBy: ['mock_yujen', 'mock_eva'],
  },

  // ── Stanford: Study ──────────────────────────────────────────────────────────
  {
    id: 'mock2',
    title: 'Green Library 3rd Floor',
    note: 'Dead quiet after 9pm. The corner near the windows has the best natural light during the day — claim it early.',
    category: 'study',
    photoURL: 'https://picsum.photos/seed/green_lib_3f/600/400',
    lat: 37.4264, lng: -122.1673,
    locationName: 'Green Library, Stanford',
    authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL,
    createdAt: ts(5),
    saveCount: 12,
    savedBy: ['mock_eva', 'guest', 'mock_maya', 'mock_alex'],
  },
  {
    id: 'mock7',
    title: 'Cecil Green Library Reading Room',
    note: 'Best kept secret on campus. Tall ceilings, wood paneling, almost zero foot traffic. Feels like studying in a manor house.',
    category: 'study',
    photoURL: 'https://picsum.photos/seed/cecilgreen_room/600/400',
    lat: 37.4264, lng: -122.1670,
    locationName: 'Cecil H. Green Library, Stanford',
    authorId: 'guest', authorName: 'Demo User', authorPhoto: MOCK_USERS.guest.photoURL,
    createdAt: ts(80),
    saveCount: 15,
    savedBy: ['mock_eva', 'mock_yujen', 'mock_maya'],
  },
  {
    id: 'mock13',
    title: 'Lathrop Library Lower Level',
    note: 'Somehow always has seats even during finals. Not as cold as Green. Quiet but not silent — good if you need some ambient sound.',
    category: 'study',
    photoURL: null,
    lat: 37.4274, lng: -122.1679,
    locationName: 'Lathrop Library, Stanford',
    authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL,
    createdAt: ts(48),
    saveCount: 11,
    savedBy: ['mock_eva', 'mock_maya', 'guest'],
  },
  {
    id: 'mock25',
    title: 'Old Chemistry Reading Room',
    note: 'Upstairs, past the labs. Tiny reading room with wood desks and old science journals. Almost nobody knows it exists. No wifi officially, but hotspot is fine.',
    category: 'study',
    photoURL: null,
    lat: 37.4280, lng: -122.1660,
    locationName: 'Old Chemistry Building, Stanford',
    authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL,
    createdAt: ts(190),
    saveCount: 7,
    savedBy: ['mock_maya', 'mock_eva'],
  },
  {
    id: 'mock12',
    title: 'Tresidder Outdoor Tables',
    note: 'Sunny tables by the coffee cart. Good for a working lunch or just sitting in the sun between classes.',
    category: 'study',
    photoURL: null,
    lat: 37.4245, lng: -122.1690,
    locationName: 'Tresidder Union, Stanford',
    authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL,
    createdAt: ts(220),
    saveCount: 3,
    savedBy: ['mock_maya'],
  },
  {
    id: 'mock30',
    title: 'Engineering Quad West Benches',
    note: 'Shaded all afternoon on the west side. Good for working outside without squinting. Quieter than it looks — almost nobody walks through on weekdays.',
    category: 'study',
    photoURL: null,
    lat: 37.4274, lng: -122.1768,
    locationName: 'Packard Engineering Quad, Stanford',
    authorId: 'guest', authorName: 'Demo User', authorPhoto: MOCK_USERS.guest.photoURL,
    createdAt: ts(285),
    saveCount: 4,
    savedBy: ['mock_maya', 'mock_yujen'],
  },

  // ── Stanford: Hidden ─────────────────────────────────────────────────────────
  {
    id: 'mock4',
    title: 'Dish Trail at Golden Hour',
    note: 'Leave campus 30 min before sunset. The ridge at the top gives you the full bay — Caltrain, the hills, everything. Bring a snack.',
    category: 'hidden',
    photoURL: 'https://picsum.photos/seed/dish_golden/600/400',
    lat: 37.4085, lng: -122.1693,
    locationName: 'Stanford Dish Trail, Stanford',
    authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL,
    createdAt: ts(30),
    saveCount: 23,
    savedBy: ['mock_eva', 'mock_yujen', 'guest', 'mock_priya', 'mock_maya'],
  },
  {
    id: 'mock9',
    title: 'Hidden Bench Behind The Thinker',
    note: "There's a bench tucked behind The Thinker that almost no one sits on. Good for reading, good for staring. Very peaceful.",
    category: 'hidden',
    photoURL: null,
    lat: 37.4340, lng: -122.1672,
    locationName: 'Rodin Sculpture Garden, Stanford',
    authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL,
    createdAt: ts(130),
    saveCount: 8,
    savedBy: ['mock_alex', 'mock_maya'],
  },
  {
    id: 'mock17',
    title: 'Inner Quad on the Weekend',
    note: 'Empty on Sundays. The arched walkways are always shaded, which somehow makes it feel like you\'re somewhere in Southern Europe. Good for a slow walk.',
    category: 'hidden',
    photoURL: 'https://picsum.photos/seed/innerquad_arches/600/400',
    lat: 37.4268, lng: -122.1676,
    locationName: 'Main Quad, Stanford',
    authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL,
    createdAt: ts(60),
    saveCount: 10,
    savedBy: ['mock_maya', 'mock_eva', 'guest'],
  },
  {
    id: 'mock18',
    title: 'Lake Lagunita North Shore',
    note: 'When it has water (winter/early spring), the north shore at dusk is legitimately beautiful. Bring someone you want to talk to.',
    category: 'hidden',
    photoURL: 'https://picsum.photos/seed/lake_lagunita_eve/600/400',
    lat: 37.4185, lng: -122.1758,
    locationName: 'Lake Lagunita, Stanford',
    authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL,
    createdAt: ts(90),
    saveCount: 16,
    savedBy: ['mock_eva', 'mock_yujen', 'mock_priya', 'mock_maya'],
  },
  {
    id: 'mock26',
    title: 'Hoover Tower Terrace',
    note: '$4 to go up, worth it once. 360-degree view of the whole campus and the bay on a clear day.',
    category: 'hidden',
    photoURL: 'https://picsum.photos/seed/hoover_terrace/600/400',
    lat: 37.4283, lng: -122.1670,
    locationName: 'Hoover Tower, Stanford',
    authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL,
    createdAt: ts(210),
    saveCount: 12,
    savedBy: ['mock_yujen', 'mock_alex', 'mock_priya', 'guest'],
  },

  // ── SF: Hidden / Outdoors ────────────────────────────────────────────────────
  {
    id: 'mock15',
    title: 'Dolores Park',
    note: 'Saturdays around noon is the move. Bi-Rite ice cream on the way in, settle on the main hill, watch the people. It\'s a whole vibe.',
    category: 'hidden',
    photoURL: 'https://picsum.photos/seed/dolores_hill/600/400',
    lat: 37.7596, lng: -122.4269,
    locationName: 'Dolores Park, Mission District, San Francisco',
    authorId: 'mock_priya', authorName: 'Priya S.', authorPhoto: MOCK_USERS.mock_priya.photoURL,
    createdAt: ts(38),
    saveCount: 19,
    savedBy: ['mock_eva', 'mock_jordan', 'mock_alex', 'mock_maya', 'guest'],
  },
  {
    id: 'mock19',
    title: 'Sutro Baths at Sunset',
    note: "Take the Land's End trail from the Cliff House side. Get there an hour before golden hour. Ruins + ocean + quiet you can't find anywhere else.",
    category: 'hidden',
    photoURL: 'https://picsum.photos/seed/sutro_dusk/600/400',
    lat: 37.7800, lng: -122.5118,
    locationName: "Sutro Baths, Land's End, San Francisco",
    authorId: 'mock_priya', authorName: 'Priya S.', authorPhoto: MOCK_USERS.mock_priya.photoURL,
    createdAt: ts(110),
    saveCount: 22,
    savedBy: ['mock_eva', 'mock_jordan', 'mock_alex', 'guest', 'mock_maya', 'mock_yujen'],
  },

  // ── Food: Palo Alto ───────────────────────────────────────────────────────────
  {
    id: 'mock5',
    title: "Zareen's",
    note: 'The chicken karahi is genuinely unreal. Go on a weekday — the line on weekends is 30+ minutes. Save room for the mango lassi.',
    category: 'food',
    photoURL: 'https://picsum.photos/seed/zareens_karahi/600/400',
    lat: 37.4489, lng: -122.1463,
    locationName: '1026 N California Ave, Palo Alto',
    authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL,
    createdAt: ts(50),
    saveCount: 21,
    savedBy: ['mock_yujen', 'mock_alex', 'mock_priya'],
  },
  {
    id: 'mock11',
    title: 'Taïm Mediterranean',
    note: "Best falafel near campus. The pink sauce is addictive. Get it as a wrap — the bowl isn't the move.",
    category: 'food',
    photoURL: 'https://picsum.photos/seed/taim_wrap/600/400',
    lat: 37.4455, lng: -122.1610,
    locationName: 'University Ave, Palo Alto',
    authorId: 'guest', authorName: 'Demo User', authorPhoto: MOCK_USERS.guest.photoURL,
    createdAt: ts(200),
    saveCount: 9,
    savedBy: ['mock_eva', 'mock_priya'],
  },
  {
    id: 'mock20',
    title: "Oren's Hummus",
    note: "Lunch rotation. The mushroom hummus with warm pita is quietly perfect. Skip dinner hours — it gets chaotic. Weekday 12:30–1:30 is the sweet spot.",
    category: 'food',
    photoURL: 'https://picsum.photos/seed/orens_pita/600/400',
    lat: 37.4468, lng: -122.1617,
    locationName: '261 University Ave, Palo Alto',
    authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL,
    createdAt: ts(120),
    saveCount: 10,
    savedBy: ['mock_eva', 'mock_priya', 'mock_yujen'],
  },
  {
    id: 'mock21',
    title: 'Vive Sol Happy Hour',
    note: '4–6pm, half-price margaritas, patio fills fast. Good spot for end-of-week decompression. The queso is non-negotiable.',
    category: 'food',
    photoURL: 'https://picsum.photos/seed/vivesol_patio/600/400',
    lat: 37.4483, lng: -122.1571,
    locationName: '236 Hamilton Ave, Palo Alto',
    authorId: 'mock_priya', authorName: 'Priya S.', authorPhoto: MOCK_USERS.mock_priya.photoURL,
    createdAt: ts(140),
    saveCount: 11,
    savedBy: ['mock_eva', 'mock_jordan', 'guest'],
  },
  {
    id: 'mock28',
    title: 'Tamarine',
    note: 'Vietnamese on University Ave — nicer than it looks from outside. The shaking beef and spring rolls are both excellent. Better for dinner.',
    category: 'food',
    photoURL: 'https://picsum.photos/seed/tamarine_viet/600/400',
    lat: 37.4468, lng: -122.1620,
    locationName: '546 University Ave, Palo Alto',
    authorId: 'mock_priya', authorName: 'Priya S.', authorPhoto: MOCK_USERS.mock_priya.photoURL,
    createdAt: ts(245),
    saveCount: 7,
    savedBy: ['mock_eva', 'mock_jordan'],
  },
  {
    id: 'mock29',
    title: 'Sichuan Chili House',
    note: 'Open until 11pm, which for Palo Alto is a miracle. The mapo tofu is legitimately spicy. Cash preferred. No frills, excellent food.',
    category: 'food',
    photoURL: 'https://picsum.photos/seed/sichuan_mapo/600/400',
    lat: 37.4492, lng: -122.1464,
    locationName: 'N California Ave, Palo Alto',
    authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL,
    createdAt: ts(260),
    saveCount: 8,
    savedBy: ['mock_jordan', 'guest', 'mock_priya'],
  },

  // ── Food: SF ─────────────────────────────────────────────────────────────────
  {
    id: 'mock23',
    title: 'Tartine Bakery',
    note: 'Get there right when they open at 8am. The morning bun is life-changing. Go on a Thursday — weekends are impossible.',
    category: 'food',
    photoURL: 'https://picsum.photos/seed/tartine_morning/600/400',
    lat: 37.7613, lng: -122.4242,
    locationName: '600 Guerrero St, Mission, San Francisco',
    authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL,
    createdAt: ts(165),
    saveCount: 18,
    savedBy: ['mock_priya', 'mock_jordan', 'mock_yujen', 'guest'],
  },

  // ── Events / Moments ─────────────────────────────────────────────────────────
  {
    id: 'mock3',
    title: 'The Axe & Palm',
    note: 'Thursday trivia nights are actually the move — go early to get a booth. The nachos are surprisingly good.',
    category: 'events',
    photoURL: 'https://picsum.photos/seed/axepalm_trivia/600/400',
    lat: 37.4295, lng: -122.1698,
    locationName: 'The Axe & Palm, Stanford',
    authorId: 'guest', authorName: 'Demo User', authorPhoto: MOCK_USERS.guest.photoURL,
    createdAt: ts(26),
    saveCount: 7,
    savedBy: ['mock_eva', 'mock_jordan'],
  },
  {
    id: 'mock6',
    title: 'Cantor Arts Center + Rodin Garden',
    note: 'Free admission always. The Rodin garden in the afternoon is a slow, good thing. Gates of Hell up close is genuinely overwhelming.',
    category: 'events',
    photoURL: null,
    lat: 37.4343, lng: -122.1669,
    locationName: '328 Lomita Dr, Stanford',
    authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL,
    createdAt: ts(72),
    saveCount: 6,
    savedBy: ['mock_alex', 'mock_maya'],
  },
  {
    id: 'mock22',
    title: 'The Booksmith',
    note: 'Haight bookstore with excellent event picks. Check their calendar — the author readings are always way more intimate than expected.',
    category: 'events',
    photoURL: null,
    lat: 37.7702, lng: -122.4475,
    locationName: '1644 Haight St, San Francisco',
    authorId: 'mock_jordan', authorName: 'Jordan K.', authorPhoto: MOCK_USERS.mock_jordan.photoURL,
    createdAt: ts(148),
    saveCount: 8,
    savedBy: ['mock_eva', 'mock_maya', 'mock_priya'],
  },
  {
    id: 'mock24',
    title: 'The Chapel',
    note: 'One of the best small venues in SF. Good sound, great sightlines from the balcony. Check their calendar constantly — lineups have been great lately.',
    category: 'events',
    photoURL: 'https://picsum.photos/seed/chapel_stage/600/400',
    lat: 37.7661, lng: -122.4195,
    locationName: '777 Valencia St, Mission, San Francisco',
    authorId: 'mock_jordan', authorName: 'Jordan K.', authorPhoto: MOCK_USERS.mock_jordan.photoURL,
    createdAt: ts(175),
    saveCount: 14,
    savedBy: ['mock_eva', 'mock_alex', 'mock_priya', 'mock_yujen'],
  },

  // ── Entertainment ─────────────────────────────────────────────────────────────
  {
    id: 'mock10',
    title: 'Old Union Ping Pong',
    note: 'Free tables, paddles at the front desk. Usually free mid-afternoon. Good procrastination spot.',
    category: 'entertainment',
    photoURL: null,
    lat: 37.4260, lng: -122.1680,
    locationName: 'Old Union, Stanford',
    authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL,
    createdAt: ts(160),
    saveCount: 4,
    savedBy: ['mock_jordan'],
  },
];

// ─── Comments ─────────────────────────────────────────────────────────────────

export const MOCK_COMMENTS = {
  mock1: [
    { id: 'c1_1', text: "Always packed but somehow worth the chaos. Get there before 10:30 or accept your fate.", authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL, createdAt: ts(1.5) },
    { id: 'c1_2', text: "Confirmed — oat milk cortado is elite. Also try the ham and cheese croissant if they have it.", authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL, createdAt: ts(0.8) },
    { id: 'c1_3', text: "The standing bar at the back has the best WiFi signal. That's my secret spot during finals.", authorId: 'mock_priya', authorName: 'Priya S.', authorPhoto: MOCK_USERS.mock_priya.photoURL, createdAt: ts(0.3) },
  ],
  mock2: [
    { id: 'c2_1', text: "The NW corner has a little alcove with two chairs and a lamp. Get there before 7pm or it's gone.", authorId: 'mock_maya', authorName: 'Maya R.', authorPhoto: MOCK_USERS.mock_maya.photoURL, createdAt: ts(4) },
    { id: 'c2_2', text: "Adding this to my finals rotation. I need a spot with actual silence, not just library-quiet.", authorId: 'guest', authorName: 'Demo User', authorPhoto: MOCK_USERS.guest.photoURL, createdAt: ts(3) },
    { id: 'c2_3', text: "Wait I've been going to 2nd floor this whole time. Moving up immediately.", authorId: 'mock_priya', authorName: 'Priya S.', authorPhoto: MOCK_USERS.mock_priya.photoURL, createdAt: ts(2) },
  ],
  mock4: [
    { id: 'c4_1', text: "Did this last Saturday at 6:40pm — absolutely worth the climb. The light was unreal.", authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL, createdAt: ts(20) },
    { id: 'c4_2', text: "Is it open during finals week?", authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL, createdAt: ts(18) },
    { id: 'c4_3', text: "Yes! It's a public trail, always open. Bring water if it's warm out.", authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL, createdAt: ts(17) },
    { id: 'c4_4', text: "The best part is nobody from campus goes here. Feels like actually leaving the bubble.", authorId: 'mock_priya', authorName: 'Priya S.', authorPhoto: MOCK_USERS.mock_priya.photoURL, createdAt: ts(12) },
  ],
  mock5: [
    { id: 'c5_1', text: "The saag paneer also goes crazy. Their chai is lowkey the best in Palo Alto.", authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL, createdAt: ts(40) },
    { id: 'c5_2', text: "Their mango lassi might be the best one I've had in the Bay. No notes.", authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL, createdAt: ts(30) },
    { id: 'c5_3', text: "Went last Friday and the wait was 45 min. Go Tuesday or Wednesday, trust me.", authorId: 'mock_priya', authorName: 'Priya S.', authorPhoto: MOCK_USERS.mock_priya.photoURL, createdAt: ts(22) },
  ],
  mock7: [
    { id: 'c7_1', text: "I've studied here 3 times and only seen 5 other people total. This is my new spot.", authorId: 'mock_maya', authorName: 'Maya R.', authorPhoto: MOCK_USERS.mock_maya.photoURL, createdAt: ts(60) },
    { id: 'c7_2', text: "There are bookable private study rooms on this floor too. Reserve 2 days ahead via the library site.", authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL, createdAt: ts(45) },
  ],
  mock9: [
    { id: 'c9_1', text: "Found this last fall and it became my reading spot for the whole quarter. The light at 3pm is perfect.", authorId: 'mock_maya', authorName: 'Maya R.', authorPhoto: MOCK_USERS.mock_maya.photoURL, createdAt: ts(90) },
    { id: 'c9_2', text: "Nobody ever sits there. Right next to The Thinker but completely in its own world.", authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL, createdAt: ts(80) },
  ],
  mock13: [
    { id: 'c13_1', text: "Found seats here at 11pm Sunday of dead week. This is essential information I should have had earlier.", authorId: 'mock_maya', authorName: 'Maya R.', authorPhoto: MOCK_USERS.mock_maya.photoURL, createdAt: ts(36) },
    { id: 'c13_2', text: "The group tables in the back have multiple outlets and are great if you need to spread out.", authorId: 'guest', authorName: 'Demo User', authorPhoto: MOCK_USERS.guest.photoURL, createdAt: ts(30) },
  ],
  mock14: [
    { id: 'c14_1', text: "Went after a late lab and stayed until closing. The grilled cheese + tomato soup combo is genuinely comforting.", authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL, createdAt: ts(10) },
    { id: 'c14_2', text: "This is such a third-week-of-the-quarter spot. Perfect energy for exactly that moment.", authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL, createdAt: ts(8) },
    { id: 'c14_3', text: "wait the coffeehouse is open until midnight?? i've been leaving the library at 10pm like a fool", authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL, createdAt: ts(5) },
  ],
  mock15: [
    { id: 'c15_1', text: "The Bi-Rite walk before settling in is mandatory. The view of downtown from the top of the hill is also underrated.", authorId: 'mock_jordan', authorName: 'Jordan K.', authorPhoto: MOCK_USERS.mock_jordan.photoURL, createdAt: ts(22) },
    { id: 'c15_2', text: "This place just makes you feel like you live a good life. Every single time.", authorId: 'mock_maya', authorName: 'Maya R.', authorPhoto: MOCK_USERS.mock_maya.photoURL, createdAt: ts(18) },
    { id: 'c15_3', text: "Bring a blanket — the grass is sometimes damp even when it looks dry.", authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL, createdAt: ts(12) },
  ],
  mock16: [
    { id: 'c16_1', text: "Went here before a conference downtown and it completely reset my brain. The morning light is incredible.", authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL, createdAt: ts(36) },
    { id: 'c16_2', text: "Perfect for slow mornings in the city. I've been back every time I'm in SF.", authorId: 'mock_jordan', authorName: 'Jordan K.', authorPhoto: MOCK_USERS.mock_jordan.photoURL, createdAt: ts(28) },
  ],
  mock18: [
    { id: 'c18_1', text: "In winter when it's full this is something else. The reflection of the hills is unreal.", authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL, createdAt: ts(70) },
    { id: 'c18_2', text: "I didn't even know this was on campus until now. How is this not more famous?", authorId: 'mock_priya', authorName: 'Priya S.', authorPhoto: MOCK_USERS.mock_priya.photoURL, createdAt: ts(55) },
    { id: 'c18_3', text: "It's seasonal — depends on the rains. But when it's full it's genuinely stunning.", authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL, createdAt: ts(50) },
  ],
  mock19: [
    { id: 'c19_1', text: "Took this walk on a clear evening in February and it was one of the best hours I've had in the Bay. No exaggeration.", authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL, createdAt: ts(80) },
    { id: 'c19_2', text: "Go late afternoon when the wind dies down. It gets cold fast near the water.", authorId: 'mock_jordan', authorName: 'Jordan K.', authorPhoto: MOCK_USERS.mock_jordan.photoURL, createdAt: ts(72) },
    { id: 'c19_3', text: "Been here 4 times and it hits different every single time. Something about the ruins.", authorId: 'mock_maya', authorName: 'Maya R.', authorPhoto: MOCK_USERS.mock_maya.photoURL, createdAt: ts(60) },
  ],
  mock23: [
    { id: 'c23_1', text: "The morning bun changed my life. Get there by 8:15am to beat the line.", authorId: 'mock_jordan', authorName: 'Jordan K.', authorPhoto: MOCK_USERS.mock_jordan.photoURL, createdAt: ts(100) },
    { id: 'c23_2', text: "Went on a Wednesday morning before class and it was honestly the highlight of the day.", authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL, createdAt: ts(90) },
  ],
  mock24: [
    { id: 'c24_1', text: "The balcony front rail is the best spot. Sound is great everywhere though.", authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL, createdAt: ts(100) },
    { id: 'c24_2', text: "Went to a folk show here last month. One of the best live music nights I've had.", authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL, createdAt: ts(90) },
    { id: 'c24_3', text: "Their calendar is genuinely good. Worth checking before any weekend trip to the Mission.", authorId: 'mock_priya', authorName: 'Priya S.', authorPhoto: MOCK_USERS.mock_priya.photoURL, createdAt: ts(80) },
  ],
  mock26: [
    { id: 'c26_1', text: "Brought my parents up and my dad said it was worth the $4 — which from him is basically a rave review.", authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL, createdAt: ts(140) },
    { id: 'c26_2', text: "The view of the Dish Trail from up there is actually wild. Never realized how close it was.", authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL, createdAt: ts(130) },
  ],
};

// ─── Collections ──────────────────────────────────────────────────────────────

export const MOCK_COLLECTIONS = [
  { id: 'coll_sf',     name: 'SF Gems',          count: 7,  visibility: 'shared'  },
  { id: 'coll_study',  name: 'Study Gems',        count: 8,  visibility: 'private' },
  { id: 'coll_summer', name: 'Summer Gems',       count: 5,  visibility: 'shared'  },
  { id: 'coll_saved',  name: 'Saved',             count: 11, visibility: 'private' },
  { id: 'coll_coffee', name: 'Coffee Runs',       count: 6,  visibility: 'shared'  },
  { id: 'coll_date',   name: 'Date-ish Spots',    count: 4,  visibility: 'private' },
  { id: 'coll_hidden', name: 'Hidden Stanford',   count: 5,  visibility: 'shared'  },
  { id: 'coll_night',  name: 'Late Night Bites',  count: 3,  visibility: 'private' },
];

// ─── User Profiles ────────────────────────────────────────────────────────────

export const MOCK_USER_PROFILES = {
  guest: {
    bio: 'exploring campus one gem at a time',
    tasteTags: ['campus walks', 'hidden spots', 'late night eats'],
    socialProof: 'new to gem',
    followers: 0,
    following: 2,
    collections: [
      { id: 'coll_saved', name: 'Saved', count: 11, visibility: 'private', icon: 'bookmark-outline', color: '#A98BBE' },
    ],
  },
  mock_eva: {
    bio: 'quiet corners, strong coffee, and places worth remembering',
    tasteTags: ['quiet study spots', 'coffee runs', 'hidden gems', 'SF days', 'art corners'],
    socialProof: '4 of your friends follow Eva',
    followers: 63,
    following: 41,
    collections: [
      { id: 'coll_sf',     name: 'SF Gems',     count: 7,  visibility: 'shared',  icon: 'location-outline', color: '#7A9FC2' },
      { id: 'coll_study',  name: 'Study Gems',  count: 8,  visibility: 'private', icon: 'book-outline',     color: '#5B7FA6' },
      { id: 'coll_coffee', name: 'Coffee Runs', count: 6,  visibility: 'shared',  icon: 'cafe-outline',     color: '#B8956A' },
    ],
  },
  mock_yujen: {
    bio: 'coffee first, then studying — usually both at the same time',
    tasteTags: ['coffee runs', 'campus discoveries', 'study spots', 'quiet mornings'],
    socialProof: 'you both saved Coupa Café',
    followers: 51,
    following: 35,
    collections: [
      { id: 'coll_summer', name: 'Summer Gems', count: 5, visibility: 'shared',  icon: 'sunny-outline', color: '#C4A882' },
      { id: 'coll_study',  name: 'Study Gems',  count: 8, visibility: 'private', icon: 'book-outline',  color: '#5B7FA6' },
      { id: 'coll_coffee', name: 'Coffee Runs', count: 6, visibility: 'shared',  icon: 'cafe-outline',  color: '#B8956A' },
    ],
  },
  mock_alex: {
    bio: 'late nights, long trails, the best food I can find under $15',
    tasteTags: ['hidden gems', 'late night eats', 'campus walks', 'food spots', 'trails'],
    socialProof: 'followed by Eva and Yujen',
    followers: 42,
    following: 28,
    collections: [
      { id: 'coll_saved',  name: 'Saved',            count: 11, visibility: 'private', icon: 'bookmark-outline', color: '#A98BBE' },
      { id: 'coll_summer', name: 'Summer Gems',      count: 5,  visibility: 'shared',  icon: 'sunny-outline',    color: '#C4A882' },
      { id: 'coll_night',  name: 'Late Night Bites', count: 3,  visibility: 'private', icon: 'moon-outline',     color: '#8A9BBE' },
    ],
  },
  mock_priya: {
    bio: 'SF-based, always hungry, always looking for the next good thing',
    tasteTags: ['SF gems', 'food spots', 'brunch spots', 'neighborhood cafes', 'parks'],
    socialProof: '2 of your friends follow Priya',
    followers: 38,
    following: 22,
    collections: [
      { id: 'coll_sf',   name: 'SF Gems',        count: 7, visibility: 'shared',  icon: 'location-outline', color: '#7A9FC2' },
      { id: 'coll_date', name: 'Date-ish Spots', count: 4, visibility: 'private', icon: 'heart-outline',    color: '#C4828A' },
    ],
  },
  mock_jordan: {
    bio: 'live music, late dinners, and places that feel alive after 10pm',
    tasteTags: ['concerts', 'late night', 'events', 'food spots', 'city nights'],
    socialProof: 'followed by Alex and Priya',
    followers: 29,
    following: 18,
    collections: [
      { id: 'coll_sf',    name: 'SF Gems',          count: 7, visibility: 'shared',  icon: 'location-outline', color: '#7A9FC2' },
      { id: 'coll_night', name: 'Late Night Bites', count: 3, visibility: 'private', icon: 'moon-outline',     color: '#8A9BBE' },
    ],
  },
  mock_maya: {
    bio: 'always looking for the quiet spot nobody else has found yet',
    tasteTags: ['quiet corners', 'reading spots', 'campus walks', 'hidden gems', 'slow mornings'],
    socialProof: 'followed by Eva',
    followers: 22,
    following: 31,
    collections: [
      { id: 'coll_hidden', name: 'Hidden Stanford', count: 5, visibility: 'shared',  icon: 'diamond-outline', color: '#C4828A' },
      { id: 'coll_study',  name: 'Study Gems',      count: 8, visibility: 'private', icon: 'book-outline',    color: '#5B7FA6' },
    ],
  },
};
