// Set to false once Firebase is configured and you have real data
export const USE_MOCK_DATA = true;

const ts = (hoursAgo) => ({
  toDate: () => new Date(Date.now() - hoursAgo * 60 * 60 * 1000),
});

export const MOCK_USERS = {
  guest:      { uid: 'guest',       displayName: 'Demo User', photoURL: 'https://i.pravatar.cc/150?img=12' },
  mock_eva:   { uid: 'mock_eva',    displayName: 'Eva W.',    photoURL: 'https://i.pravatar.cc/150?img=47' },
  mock_yujen: { uid: 'mock_yujen',  displayName: 'Yujen L.',  photoURL: 'https://i.pravatar.cc/150?img=33' },
  mock_alex:  { uid: 'mock_alex',   displayName: 'Alex C.',   photoURL: 'https://i.pravatar.cc/150?img=15' },
};

export const MOCK_PINS = [
  {
    id: 'mock1',
    title: 'Coupa Café',
    note: 'Get the cortado — ask for oat milk. Best spot to work before 11am, it gets packed.',
    category: 'coffee',
    photoURL: 'https://picsum.photos/seed/coupa/600/400',
    lat: 37.4281, lng: -122.1651,
    locationName: 'School of Business, Stanford',
    authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL,
    createdAt: ts(2),
    saveCount: 14,
    savedBy: ['mock_yujen', 'mock_alex', 'guest'],
  },
  {
    id: 'mock2',
    title: 'Green Library 3rd Floor',
    note: 'Dead quiet after 9pm. The corner near the windows has the best natural light.',
    category: 'study',
    photoURL: null,
    lat: 37.4264, lng: -122.1673,
    locationName: 'Green Library, Stanford',
    authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL,
    createdAt: ts(5),
    saveCount: 9,
    savedBy: ['mock_eva', 'guest'],
  },
  {
    id: 'mock3',
    title: 'The Axe & Palm',
    note: 'Thursday trivia nights are so fun — go early to grab a booth.',
    category: 'events',
    photoURL: 'https://picsum.photos/seed/axepalm/600/400',
    lat: 37.4295, lng: -122.1698,
    locationName: 'The Axe & Palm, Stanford',
    authorId: 'guest', authorName: 'Demo User', authorPhoto: MOCK_USERS.guest.photoURL,
    createdAt: ts(26),
    saveCount: 6,
    savedBy: ['mock_eva'],
  },
  {
    id: 'mock4',
    title: 'Dish Trail Sunset Spot',
    note: 'Go 30 min before sunset. The view from the top is unreal — bring a snack.',
    category: 'hidden',
    photoURL: 'https://picsum.photos/seed/dishtrail/600/400',
    lat: 37.4085, lng: -122.1693,
    locationName: 'Dish Trail, Stanford',
    authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL,
    createdAt: ts(30),
    saveCount: 18,
    savedBy: ['mock_eva', 'mock_yujen', 'guest'],
  },
  {
    id: 'mock5',
    title: "Zareen's",
    note: 'The chicken karahi is genuinely unreal. Go on a weekday — the line on weekends is crazy.',
    category: 'food',
    photoURL: 'https://picsum.photos/seed/zareens/600/400',
    lat: 37.4489, lng: -122.1463,
    locationName: '1026 N California Ave, Palo Alto',
    authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL,
    createdAt: ts(50),
    saveCount: 21,
    savedBy: ['mock_yujen', 'mock_alex'],
  },
  {
    id: 'mock6',
    title: 'Cantor Arts Center',
    note: 'Free admission always. The Rodin garden is perfect for a slow afternoon.',
    category: 'events',
    photoURL: null,
    lat: 37.4343, lng: -122.1669,
    locationName: '328 Lomita Dr, Stanford',
    authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL,
    createdAt: ts(72),
    saveCount: 4,
    savedBy: ['mock_alex'],
  },
  {
    id: 'mock7',
    title: 'Moffitt 4th Floor',
    note: 'Silent floor, almost always has open seats. Way less crowded than the 3rd.',
    category: 'study',
    photoURL: null,
    lat: 37.4275, lng: -122.1685,
    locationName: 'Meyer Library, Stanford',
    authorId: 'guest', authorName: 'Demo User', authorPhoto: MOCK_USERS.guest.photoURL,
    createdAt: ts(80),
    saveCount: 11,
    savedBy: ['mock_eva', 'mock_yujen'],
  },
  {
    id: 'mock8',
    title: 'Philz Coffee',
    note: 'Iced Silken Splendor, no sugar. The patio in the back is underrated.',
    category: 'coffee',
    photoURL: 'https://picsum.photos/seed/philz/600/400',
    lat: 37.4421, lng: -122.1601,
    locationName: '855 El Camino Real, Palo Alto',
    authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL,
    createdAt: ts(100),
    saveCount: 7,
    savedBy: ['guest'],
  },
  {
    id: 'mock9',
    title: 'Hidden Rodin Bench',
    note: "There's a bench behind The Thinker that almost nobody sits at. Great for reading.",
    category: 'hidden',
    photoURL: null,
    lat: 37.4340, lng: -122.1672,
    locationName: 'Cantor Arts Center, Stanford',
    authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL,
    createdAt: ts(130),
    saveCount: 5,
    savedBy: ['mock_alex'],
  },
  {
    id: 'mock10',
    title: 'Old Union Ping Pong',
    note: 'Free tables, paddles at the front desk. Usually free mid-afternoon.',
    category: 'entertainment',
    photoURL: null,
    lat: 37.4260, lng: -122.1680,
    locationName: 'Old Union, Stanford',
    authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL,
    createdAt: ts(160),
    saveCount: 3,
    savedBy: [],
  },
  {
    id: 'mock11',
    title: 'Taïm Mediterranean',
    note: 'Best falafel near campus. The pink sauce is addictive.',
    category: 'food',
    photoURL: 'https://picsum.photos/seed/taim/600/400',
    lat: 37.4455, lng: -122.1610,
    locationName: 'University Ave, Palo Alto',
    authorId: 'guest', authorName: 'Demo User', authorPhoto: MOCK_USERS.guest.photoURL,
    createdAt: ts(200),
    saveCount: 8,
    savedBy: ['mock_eva'],
  },
  {
    id: 'mock12',
    title: 'Tresidder Outdoor Tables',
    note: 'Sunny tables by the coffee cart. Great for lunch meetings or just vibing.',
    category: 'study',
    photoURL: null,
    lat: 37.4245, lng: -122.1690,
    locationName: 'Tresidder Union, Stanford',
    authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL,
    createdAt: ts(220),
    saveCount: 2,
    savedBy: [],
  },
];

export const MOCK_COMMENTS = {
  mock1: [
    { id: 'c1', text: 'This place is always packed but so worth it 🙌', authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL, createdAt: ts(1) },
    { id: 'c2', text: 'Confirmed — oat milk cortado is elite', authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL, createdAt: ts(0.5) },
  ],
  mock4: [
    { id: 'c3', text: 'Did this last week, 10/10 highly recommend going with friends', authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL, createdAt: ts(20) },
    { id: 'c4', text: 'Is it still open during finals?', authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL, createdAt: ts(18) },
    { id: 'c5', text: 'Yes!! Open always, it\'s just a trail', authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL, createdAt: ts(17) },
  ],
  mock5: [
    { id: 'c6', text: 'The saag paneer also goes crazy', authorId: 'mock_alex', authorName: 'Alex C.', authorPhoto: MOCK_USERS.mock_alex.photoURL, createdAt: ts(40) },
    { id: 'c7', text: 'Their mango lassi is undefeated', authorId: 'mock_yujen', authorName: 'Yujen L.', authorPhoto: MOCK_USERS.mock_yujen.photoURL, createdAt: ts(30) },
  ],
  mock7: [
    { id: 'c8', text: 'There are also private study rooms on this floor you can book', authorId: 'mock_eva', authorName: 'Eva W.', authorPhoto: MOCK_USERS.mock_eva.photoURL, createdAt: ts(60) },
  ],
};
